recipes/urls.py
from django.urls import path

from recipes.views import (
    RecipeCreateView,
    RecipeDeleteView,
    RecipeUpdateView,
    log_rating,
    RecipeDetailView,
    RecipeListView,
    ShoppingItemListView,
    shoppingitems_delete,
    shoppingitem_create,
)

urlpatterns = [
    path("", RecipeListView.as_view(), name="recipes_list"),
    path("<int:pk>/", RecipeDetailView.as_view(), name="recipe_detail"),
    path("<int:pk>/delete/", RecipeDeleteView.as_view(), name="recipe_delete"),
    path("new/", RecipeCreateView.as_view(), name="recipe_new"),
    path("<int:pk>/edit/", RecipeUpdateView.as_view(), name="recipe_edit"),
    path("<int:recipe_id>/ratings/", log_rating, name="recipe_rating"),
    path(
        "shopping_items/",
        ShoppingItemListView.as_view(),
        name="shoppingitem_list",
    ),
    path(
        "shopping_items/delete/",
        shoppingitems_delete,
        name="shoppingitems_delete",
    ),
    path(
        "shopping_items/create/",
        shoppingitem_create,
        name="shoppingitem_create",
    ),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("meal_plans/", include("meal_plans.urls")),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

recipes/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# from django.contrib.auth.models import User
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=125)
    author = models.ForeignKey(
        USER_MODEL, related_name="recipes", on_delete=models.CASCADE, null=True
    )
    # if we have a yser instance, we can do .recipes and get all receipes
    # author = models.CharField(max_length=100)
    description = models.TextField()
    image = models.URLField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    servings = models.PositiveSmallIntegerField(
        null=True,
        validators=[
            MinValueValidator(1),
        ],
    )

    def __str__(self):
        if self.author:
            return self.name + " by " + self.author.username
        else:
            return self.name


class Measure(models.Model):
    name = models.CharField(max_length=30, unique=True)
    abbreviation = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name


class FoodItem(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    amount = models.FloatField(validators=[MaxValueValidator(20)])
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ingredients",
        on_delete=models.CASCADE,
    )
    measure = models.ForeignKey("Measure", on_delete=models.PROTECT)
    food = models.ForeignKey("FoodItem", on_delete=models.PROTECT)

    def __str__(self):
        amount = str(self.amount)
        measure = self.measure.name
        food = self.food.name
        return amount + " " + measure + " " + food


class Step(models.Model):
    recipe = models.ForeignKey(
        "Recipe",
        related_name="steps",
        on_delete=models.CASCADE,
    )
    order = models.PositiveSmallIntegerField()
    directions = models.CharField(max_length=300)
    food_items = models.ManyToManyField("FoodItem", blank=True)

    def __str__(self):
        return str(self.order) + ". " + self.directions


class Rating(models.Model):
    value = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1),
        ]
    )
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ratings",
        on_delete=models.CASCADE,
    )


class ShoppingItem(models.Model):
    author = models.ForeignKey(
        USER_MODEL,
        related_name="shoppingitem",
        on_delete=models.CASCADE,
        null=True,
    )
    food_item = models.ForeignKey(
        "FoodItem",
        related_name="food_item",
        on_delete=models.PROTECT,
    )

    def __str__(self):
        return self.food_item.name

recipes/forms.py
from django import forms


# from recipes.models import Recipe
from recipes.models import Rating


# class RecipeForm(forms.ModelForm):
#     class Meta:
#         model = Recipe
#         fields = [
#             "name",
#             "author",
#             "description",
#             "image",
#         ]


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["value"]

recipes/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin


from recipes.forms import RatingForm


# from recipes.forms import RecipeForm
from recipes.models import Recipe, ShoppingItem, Ingredient

from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_http_methods
from django.db import IntegrityError


def log_rating(request, recipe_id):
    if request.method == "POST":
        form = RatingForm(request.POST)
        try:
            if form.is_valid():
                rating = form.save(commit=False)
                rating.recipe = Recipe.objects.get(pk=recipe_id)
                rating.save()
            return redirect("recipe_detail", pk=recipe_id)
        except Recipe.DoesNotExist:
            return redirect("recipes_list")


class RecipeListView(ListView):
    model = Recipe
    template_name = "recipes/list.html"
    paginate_by = 4

    # def get_queryset(self):
    #     # Get the normal queryset
    #     queryset = super().get_queryset()

    #     print("this is the queryset \n")

    #     # Print it to see what's in it
    #     print(queryset)

    #     # Return it like nothing ever happened
    #     return queryset

    # def get_context_data(self, **kwargs):
    #     # Let the parent class get the context for
    #     # the actual Post for its detail
    #     context = super().get_context_data(**kwargs)

    #     # Print it out to see what's in it
    #     from pprint import pprint

    #     pprint(context)

    #     # Return it like nothing ever happened
    #     return context


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "recipes/detail.html"

    # # Get the value from the
    # # request.POST dictionary using the "get" method
    # servings_input = 3  # Recipe.request.GET.get("servings_input")

    # # # Multiply values of ingredient.amount by servings_input
    # for recipe in Recipe.objects.all():
    #     for ing in recipe.ingredients.all():
    #         ing.amount *= servings_input

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rating_form"] = RatingForm()
        # context["shoppingitem_list"] = self.request.user.shoppingitem.all()

        # Create a new empty list and assign it to a variable
        foods = []

        # For each item in the user's shopping items, which we
        # can access through the code
        # self.request.user.shopping_items.all()
        for item in self.request.user.shoppingitem.all():
            # Add the shopping item's food to the list
            foods.append(item.food_item)

        # Put that list into the context
        context["food_in_shopping_list"] = foods

        # The self.request.GET property is a dictionary
        # Get the value out of there associated with the
        #   key "servings"
        # Store in the context dictionary with the key
        #   "servings"
        context["servings"] = self.request.GET.get("servings_input")

        return context

    # def get_queryset(self):
    #     # Get the normal queryset
    #     queryset = super().get_queryset()

    #     print("this is the queryset \n")

    #     # Print it to see what's in it
    #     print(queryset)

    #     # Return it like nothing ever happened
    #     return queryset

    # def get_context_data(self, **kwargs):
    #     # Let the parent class get the context for
    #     # the actual Post for its detail
    #     context = super().get_context_data(**kwargs)

    #     # Print it out to see what's in it
    #     from pprint import pprint

    #     pprint(context)

    #     # Return it like nothing ever happened
    #     return context


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = "recipes/new.html"
    fields = ["name", "description", "servings", "image"]
    success_url = reverse_lazy("recipes_list")

    # override form_valid
    def form_valid(self, form):
        # get logged in user
        user = self.request.user
        # set author attribute of recipe to logged in user
        form.instance.author = user
        return super().form_valid(form)


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    template_name = "recipes/edit.html"
    fields = ["name", "description", "servings", "image"]
    success_url = reverse_lazy("recipes_list")

    # override form_valid
    def form_valid(self, form):
        # get logged in user
        user = self.request.user
        # set author attribute of recipe to logged in user
        form.instance.author = user
        return super().form_valid(form)

    # def get_queryset(self):
    #     # Get the normal queryset
    #     queryset = super().get_queryset()

    #     print("this is the queryset \n")

    #     # Print it to see what's in it
    #     print(queryset)

    #     # Return it like nothing ever happened
    #     return queryset

    # def get_context_data(self, **kwargs):
    #     # Let the parent class get the context for
    #     # the actual Post for its detail
    #     context = super().get_context_data(**kwargs)

    #     # Print it out to see what's in it
    #     from pprint import pprint

    #     pprint(context)

    #     # Return it like nothing ever happened
    #     return context


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    template_name = "recipes/delete.html"
    success_url = reverse_lazy("recipes_list")

    # super cool if would only allow user who owns recipe to edit/delete


class ShoppingItemListView(ListView):
    model = ShoppingItem
    template_name = "shoppingitem_list.html"
    paginate_by = 10

    def get_queryset(self):
        return ShoppingItem.objects.filter(author=self.request.user)


@require_http_methods(["POST"])
@login_required(login_url="registration/login")
def shoppingitem_create(request):

    # Get the value for the "ingredient_id" from the
    # request.POST dictionary using the "get" method
    ingredient_id = request.POST.get("ingredient_id")

    # Get the specific ingredient from the Ingredient model
    # using the code
    # Ingredient.objects.get(id=the value from the dictionary)
    ingredient = Ingredient.objects.get(id=ingredient_id)

    # Get the current user which is stored in request.user
    user = request.user

    try:
        # Create the new shopping item in the database
        # using ShoppingItem.objects.create(
        #   food_item= the food item on the ingredient,
        #   user= the current user
        # )
        ShoppingItem.objects.create(
            food_item=ingredient.food,
            author=user,
        )
    except IntegrityError:
        pass

    # Go back to the recipe page with a redirect
    # to the name of the registered recipe detail
    # path with code like this
    # return redirect(
    #     name of the registered recipe detail path,
    #     pk=id of the ingredient's recipe
    # )
    return redirect("recipe_detail", pk=ingredient.recipe.id)


@require_http_methods(["POST"])
@login_required(login_url="registration/login")
def shoppingitems_delete(request):

    # Get the current user which is stored in request.user
    user = request.user

    # Delete all of the shopping items for the user
    # using code like
    # ShoppingItem.objects.filter(user=the current user).delete()
    ShoppingItem.objects.filter(author=user).delete()

    # Go back to the shopping item list with a redirect
    # to the name of the registered shopping item list
    # path with code like this
    # return redirect(
    #     name of the registered shopping item list path
    # )
    return redirect("shoppingitem_list")

recipes/templates/recipes/delete.html
{% extends 'base.html' %}

{% block content %}
<main>
  <div class="delete-form">
    <form method="post">
      {% csrf_token %}
      <p>Are you sure you want to delete "{{ recipe }}"?</p>
      {{ form.as_p }}
      <div>
        <button class="button">Delete</button>
      </div>
    </form>
  </div>
</main>
{% endblock content %}

recipes/templates/recipes/detail.html
{% extends 'base.html' %}

{% load markdownify %}

{% block content %}
<main class="recipe-detail">
  <div>
    <a href="{% url 'recipe_edit' recipe.id %}">Edit</a>
    <a href="{% url 'recipe_delete' recipe.id %}">Delete</a>
  </div>
  {% if recipe.image %}
  <img src="{{ recipe.image }}" class="pull-right">
  {% endif %}
  <h1>{{ recipe.name }}</h1>
  <h2>Author: {{ recipe.author | default_if_none:"Unknown" }}</h2>
  <p>
    Created on {{ recipe.created }} |
    Updated on {{ recipe.updated }}
  </p>

  {% if recipe.servings %}

  {% if servings %}
  {% load resizer %}
  <p>
    Serves {{ servings }}
  </p>
  {% else %}
  <p>
    Serves {{ recipe.servings }}
  </p>
  {% endif %}


  <form method="get">
    <div class="rating-form-grid">
      <label for="id_servings">Servings: </label>
      <input name="servings_input" id="id_servings" type="number" required="True" min="1">
      <button class="button">Resize</button>
    </div>
  </form>

  {% endif %}

  <form method="post" action="{% url 'recipe_rating' recipe.id %}">
    {% csrf_token %}
    <div class="rating-form-grid">
      {{ rating_form.as_p }}
      <button class="button">Rate</button>
    </div>
  </form>
  <p>Tags: {% for tag in recipe.tags.all %}{{ tag.word }} {% endfor %}</p>
  {{ recipe.description | markdownify }}
  <h2>Ingredients</h2>
  <table>
    <thead>
      <tr>
        <th colspan="2">Amount</th>
        <th>Food item</th>
      </tr>
    </thead>
    <tbody>

      {% for ingredient in recipe.ingredients.all %}

      <tr>
        <td>{{ ingredient|resize_to:servings }}</td>
        <td>{{ ingredient.measure.name }}</td>
        <td>{{ ingredient.food.name }}</td>

        {% if ingredient.food not in food_in_shopping_list %}
        <td>
          <form method="post" action="{% url 'shoppingitem_create' %}">
            {% csrf_token %}
            <!-- identifies ingredient_id for each food item for a given recipe -->
            <input name="ingredient_id" type="hidden" value="{{ ingredient.id }}">
            <button>+ shopping list</button>
          </form>
        </td>
        {% endif %}

      </tr>
      {% endfor %}
    </tbody>
  </table>
  <h2>Steps</h2>
  <ol>
    {% for step in recipe.steps.all %}
    <li>{{ step.directions }}</li>
    {% endfor %}
  </ol>
</main>
{% endblock content %}

recipes/templates/recipes/edit.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button class="button">Update</button>
    </div>
  </form>
</main>
{% endblock content %}

recipes/templates/recipes/list.html
{% extends 'paginate.html' %}

{% block content %}
<main class="recipe-grid">
  {% for recipe in recipe_list %}
  <div class="recipe-card">
    <h2 class="recipe-card-title">
      <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
    </h2>
    <p class="recipe-card-date">{{ recipe.updated }}</p>
  </div>
  {% endfor %}
</main>
{% endblock content %}

recipes/templates/recipes/new.html
{% extends 'base.html' %}

{% block pagination %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock pagination %}

recipes/templates/recipes/shoppingitem_list.html
{% extends 'paginate.html' %}

{% block content %}
<main class="recipe-grid">
  <div class="recipe-card">
    <h1 class="recipe-card-title">
      {{ user.username }}'s Shopping List
    </h1>
    <ul>
      {% for item in shoppingitem_list %}
      <li>{{ item }}</li>
      {% endfor %}
    </ul>
    <!-- <form method="post" action="/recipes/shopping_items/delete/"> -->
    <form method="post" action="{% url 'shoppingitems_delete' %}">

      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button class="button">Delete All</button>
      </div>
    </form>
  </div>
</main>
{% endblock content %}